Notebook'lar hücre dediğimiz yapılardan oluşur. Yukarıdan bu hücreleri 'Code' ve 'Markdown' olarak seçebiliriz.

* İki satır arası boşluk için: Satır sonuna iki tane boşluk bırak veya <'br'> yaz

**Code**: Python kodlarını çalıştırabildiğimiz alandır. Shift+enter ile çalıştırılabilir. <br>
**Markdown**: Norlarımızı zengin bir şekilde oluşturabilmemizi sağlayan alandır

_italik_

* Madde

> Alıntı
>> Alıntı2


#### Tablolar: 
| Başlık 1 | Başlık 2 | Başlık 3 |
|----------|----------|----------|
| İçerik 1  | İçerik 2  | İçerik 3  |
| İçerik 4  | İçerik 5  | İçerik 6  |


#### Yatay çizgi:
***


#### Görev Listesi:
- [x] Yapıldı
- [ ] Yapılacak
- [ ] İncelenecek

In [3]:
print("a")

a


## **NumPy Nedir?**
Açılımı Numerical Python'dır. Python'ın bazı numerik işlemlerde yetersiz kaldığı noktalarda ihtiyaçlarımızı gidermek için çıkmış bir modüldür.  
-> Lineer Cebir'in bir alt dalı gibi düşünülmelidir.


* Bilimsel hesaplamalar için kullanılır.
* Arraylar / Çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Temelleri 1995 yılında içersinde Guido Van Rossum da olan bir topluluk tarafından atılmıştır ve 2005'te Travis Oliphant hayata geçmiştir.
* Kullanacağımız npArray, Listelere benzerdir. Farkı ise verimli veri saklama ve vektörel operasyonlardır.


#### **Neden NumPy?**
* Daha üst seviye işlemleri daha kolay şekilde yapmamıza olanak sağlar
* Maliyetleri de çok azaltır(Memorization)
* Aşağıdaki hücrelerde sağladığı kolaylıklara bakalım:

In [95]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])

In [97]:
a*b #Gördüğümüz gibi arrayler arası kolayca çarpma yapabiliyoruz

array([ 2,  8, 18, 32])

***
***
### **Array**
Tek boyutlu array = **Vektör**  
İki boyutlu array = **Matrix**

* İstersek array'lerin type'ını belirleyebiliriz:
> np.array([1,2,3,4], dtype = "float32")

* Her elemanı 0 olan array oluşturabiliriz:
> np.zeros(5)
>> np.zeros(5, dtype="int")

* Aynı şekilde her elemanı 1 olan array de oluşturabiliriz ve hatta iki boyutlu array de oluşturabiliriz:
  > np.ones(5)
  >> np.ones((3,5))

* Eğer belli bir sayıdan oluşan bir array oluşturmak istiyorsak:
  > np.full((3,5) , 22)

* Belirli bir aralıkta belirlediğimiz aralıklarla artan array de oluşturabiliriz:
  > np.arange(0,31 , 3) **(kaçtan, kaça, kaçar kaçar)**

* İki değer arasında istediğimiz sayıda eleman içeren array de oluştutabiliriz:
  > np.linspace(0,1 , 10) **0 ile 1 arasında 10 tane eleman olacak şekilde array oluşturur**

* İstediğimiz ortalama(average) ve standart sapmaya sahip olan ve istediğimiz boyuttta array oluşturma:
  > np.random.normal(10, 4, (4,4)) **(ortalama, ss, arrayBoyutu)**

* Ortlama ve ss ile uğraşmadan da istediğimiz boyutta random array oluşturabiliriz:
  > np.random.randint(low, high=None, size=None, dtype=int)  
    np.random.randint(0, 10 , (4,4)) **(kaçtan, kaça, arrayBoyutu)**  
    np.random.randint(0, 5 , 11)
  >> np.random.randint(10, (4,4)) **Başlangıcı 0 olarak kabul eder ve aralığı 0-10 alır**

In [117]:
a = np.arange(0,31 , 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

***
#### **Array Özellikleri**
* **ndim:** Array'in boyut bilgisini verir
* **shape:** Hem boyut bilgisini verir hem de eleman sayısını verir
  > (10,) şeklinde verirse 1 boyutlu ve 10 elemana sahip demektir
  >> (3, 4) şeklinde verirse 3 satır 4 sütunlu iki boyutlu bir arraydir 
* **size:** Array'in toplam eleman sayısını verir
* **dtype:** Array'in veri tipini verir



In [109]:
a = np.random.randint(0, 10 , (3,4))
a.shape

(3, 4)

***
#### **Yeniden Şekillendirme (Reshaping)**
* Mesela elimizde 1den 10a kadar sayıların olduğu 9 elemanlı tek boyutlu bir array var ve biz bu arrayi iki boyutlu 3x3 bir array yapmak istiyoruz:
  > a = np.arange(1,10)  
    a.reshape((3,3))

In [177]:
a = np.arange(1,10)
b = a.reshape((3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***
#### **Birleştirme (Concatenation)**
* Tek Boyutlu:
  > a = np.array([1,2,3,4])  
    b = np.array([5,6,7,8])  
    c = np.array([1,3,5])
    >> np.concatenate([a,b,c])

* İki boyutlu:
  > a = np.array( [[1,2,3], [4,5,6]] )
  > b = np.array( [[7,8,9], [1,3,5]] )
    >> np.concatenate([a,b])  

**NOT:** Peki biz satır bazlı birşeltirmek istersek:
> np.concatenate([a,b] , axis = 1)  **Normalde axis'in default değeri 0dır ve bu da sütun bazlı birleştirme yapar**

In [175]:
a = np.array([1,2,3,4])  
b = np.array([5,6,7,8])
c = np.array([1,3,5])
d = np.concatenate([a,b,c])
print(d)
print(" ")


a = np.array( [[1,2,3],
               [4,5,6]] )
b = np.array( [[7,8,9],
               [1,3,5]] )
c = np.concatenate([a,b])
print(c)
print(" ")


a = np.array( [[1,2,3],
               [4,5,6]] )
b = np.array( [[7,8,9,10],
               [1,3,5,7]] )
c = np.concatenate([a,b] , axis = 1)

print(c)

[1 2 3 4 5 6 7 8 1 3 5]
 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 5]]
 
[[ 1  2  3  7  8  9 10]
 [ 4  5  6  1  3  5  7]]


***
#### **Ayırma (Splitting)**
* a = np.array([1,2,3,99,99,3,2,1])  
  np.split(a, [3, 5]) **(Array, [kadar, kadar])**

* Peki bu ayırdığımız arrayleri nasıl saklayacağız:  
  k,l,m = np.split(a, [3, 5])


##### **İki Boyutlu ayırma**
* Diyelim ki elimizdeki 4x4lük bir array'in ilk iki satırını bir array kalan iki satırını başka bir arraye ayıracağız:  
  x = np.arange(16).reshape(4,4)  
  np.split(x, [2]) **(array, [kadar])**  
  bottom, top = np.split(x, [2])

In [194]:
a = np.array([1,2,3,99,99,3,2,1])
k,l,m = np.split(a, [3, 5])
print(k,l,m)
print(" ")

x = np.arange(16).reshape(4,4)
bottom, top = np.split(x, [2])
print(bottom)
print(top)

[1 2 3] [99 99] [3 2 1]
 
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


***
#### **Sıralama (Sorting)**
* v = np.array([2,1,4,8,5])  
  np.sort(v)

* Bunu biz normal python içerisinde de NumPy'a ihtiyaç duymadan yapabiliyorduk ama v.sort() yaptığımız an numpy array'imizin türünü değiştirir ve normal array olarak tanımlar.

##### **İki Boyutlu Sıralama**
* Diyelim ki biz 3x3lük arrayin satırlarını sıramalak istiyorum.  
  m = np.random.normal(20, 5, (3,3))  
  np.sort(m, axis=1)

* Sütunlarını sıralamak istersek:
  np.sort(m, axis=0)

In [214]:
m = np.random.normal(20, 5, (3,3))  
a = np.sort(m, axis=1)
print(n)
print()

b = np.sort(m, axis=0)
print(b)

[[11.33748784 16.87943449 23.83334123]
 [18.5023492  22.69072285 28.7893152 ]
 [12.92376904 16.52635104 18.24242182]]

[[16.49817916 10.96631571 14.96151904]
 [18.34727596 22.36273952 24.49934744]
 [24.97555679 28.23708321 24.63181349]]


***
#### **Indeks ile Elemanlara Erişim**
* a[0]
* sondaki elemana da erişebiliriz: a[-1]
* Elemanlar üzerinden değişiklik yapabiliriz: a[0] = 5
  

##### **İki boyutlu array**
* m[0,0]

#### **Slicing ile Elemanlara Erişim**
* Slice anlamı dilimlemektir yani aslında bir yerden bir yere kadar olan elemanlara erişmek istediğimizde kullanırız
* a[0:3] , a[:3] , a[3:]
* İkişer ikişer atlamak için a[1::2]

In [223]:
a = np.array([1,2,3,4])
print(a[-1])

4


***
#### **Slicing ile Elemanlara Erişim**
* Slice anlamı dilimlemektir yani aslında bir yerden bir yere kadar olan elemanlara erişmek istediğimizde kullanırız
* a[0:3] , a[:3] , a[3:]
* İkişer ikişer atlamak için a[1::2]

##### **İki boyutlu array**
* a[: , 0] -> tüm satırları seç, 0. sütunu seç. Ve güzel tarafı bunu yine bize bir array olarak verir ve bunu başka bir array değişkenine atayabiliriz
* a[0 , :] -> 0. sütun elemanlarını verir
* Bunları mixleyerek de çalıştırabilirliz:  
  a[0:2 , 0:3] -> İlk iki satırın ilk üç sütununu verir  
  a[:: , :2] -> Tüm satırları al, ve onların sadece 0 ve 1. sütununu ver yani 2. indekse kadar

In [234]:
a = np.random.randint(10, size=(5,5))
a

array([[7, 7, 0, 7, 5],
       [3, 1, 7, 3, 9],
       [3, 7, 6, 0, 4],
       [7, 6, 4, 1, 5],
       [2, 4, 6, 8, 7]])

In [242]:
b = a[:, 0]
b

array([7, 3, 3, 7, 2])

In [244]:
a[0:2 , 0:3]

array([[7, 7, 0],
       [3, 1, 7]])

***
#### **Alt Küme Bağımlılık/Bağımsızlık**
* Diyelim bir array oluşturduk: a = np. random.randint(10, size = (5, 5))
* Ve sonra bu arraydan bir alt küme oluşturduk: sub_a = a[0:3 , 0:2]
* Peki şu an sub_a üzerinden bir değişiklik yapalım: sub_a[0,0] = 9999
* Yapılan işlem 'a' array'ini etkileyecek mi? **Evet!!!**

##### Peki bunun olmamasını istiyorsak?
* copy() methodu kullanmalıyız:  
  sub_a2 = a[0:2 , 0:3]. copy()

In [258]:
a = np. random.randint(10, size = (5, 5))
sub_a = a[0:2 , 0:3]
sub_a[0,0] = 9999
print(sub_a)
print()
print(a)

[[9999    4    1]
 [   0    7    7]]

[[9999    4    1    9    2]
 [   0    7    7    8    0]
 [   8    6    5    9    2]
 [   6    7    1    9    0]
 [   5    8    1    9    8]]


***
#### **Fancy İndex ile Elemanlara Erişim**
* Önce eleman filtreleme array'i ıluşturuyoruz: myFilter = [1,3,9]
* Daha sonra oluşturduğumuz bu array'i filtrelemek istediğimiz array içerisinde kullanıyoruz: a[myFilter]

##### **İki Boyutlu**
* a = np.arange(9).reshape((3,3))  
  line = [0,1]  
  column = np.array([1,2])  
  a[line, column]  

In [280]:
a = np.arange(0,50,3)
myFilter = [1,3,9]
a[myFilter]

array([ 3,  9, 27])

In [294]:
a = np.arange(9).reshape((3,3))
line = [0,1]
column = np.array([1,2])
a[line, column]

array([1, 5])

***
#### **Fancy ile Koşullu Eleman İşlemleri**
* Mesela biz bir arraydeki 3'ten küçük elemanları listelemek istiyoruz: a = np.arange(0,50)  
  a < 3 -> Bu bize 3ten küçükler için 'True', büyük ve eşitler için 'False' verir
* Peki direkt elemanların kendisine erişmek istersek:  
  v[v<3]

######
* İstersek tüm elemanları da bir işleme tabi tutabiliriz:  
  a*5 -> a'nın tüm elemanlarını 5 ile çarpar

In [323]:
a = np.random.randint(0,5,12)
a*2

array([2, 0, 6, 2, 0, 2, 8, 4, 0, 6, 0, 4])

***
#### **Matematiksel İşlemler**
* np.cos(180)  
  np.log(array), np.log10(array)
  
##### **İki Bilinmeyenli Denklem**
* Bunun için NumPy'ın lineer cebir için üretilmiş alt paketi olan '**linalg**' kullanıyor olacağız. 
* 5x0 + x1 = 12  
  x0 + 3x1 = 10
> Yukarıdaki iki bilinmeyenli denkemi çözelim:  
  a = np.array( [[5,1] , [1,3]] )  
  b = np.array([12,10])
>> solution = np.linalg.solve(a,b)

In [344]:
a = np.array([[5,1] , [1,3]])
b = np.array([12,10])
solution = np.linalg.solve(a,b)
solution

array([1.85714286, 2.71428571])