In [1]:
import numpy as np

In [10]:
a = np.random.randint(10, size=(5,5))
a

array([[9, 3, 3, 7, 6],
       [8, 1, 8, 6, 1],
       [5, 9, 6, 6, 5],
       [8, 0, 1, 7, 1],
       [6, 9, 6, 7, 4]])

In [16]:
a[0][0]

9

In [24]:
a[:,0]

array([7, 6, 6, 7, 7])

In [27]:
a[3,:]

array([8, 0, 1, 7, 1])

In [35]:
a[0:2 , 0:3]

array([[9, 3, 3],
       [8, 1, 8]])